name: alkhal
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sqflite: ^2.4.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  share_plus: ^7.1.0
  connectivity_plus: ^6.0.3
  http: ^1.2.1
  fl_chart: ^0.69.2
  workmanager: ^0.5.2
  flutter_dotenv: ^5.2.1  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: me
      fonts:
        - asset: fonts/me.ttf
